# Generated by Django 3.2.8 on 2021-11-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgSrc', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('rating', models.FloatField(default=0)),
                ('shareNum', models.IntegerField(default=0)),
                ('commentNum', models.IntegerField(default=0)),
                ('author', models.CharField(max_length=50)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('num_of_ser', models.IntegerField(default=0)),
                ('prep_time', models.IntegerField(default=0)),
                ('cook_time', models.IntegerField(default=0)),
                ('ingredient', models.TextField(blank=True)),
                ('instruction', models.TextField(blank=True)),
            ],
        ),
    ]
