# Generated by Django 3.2.8 on 2021-11-04 15:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinese_food_recipes', '0003_alter_recipes_imgsrc'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='collected_by',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=[], size=None),
        ),
    ]
